CC = gcc
CFLAGS = -Wall -pedantic
ELF_DIR = ./executables/
TARGETS = tugas2_1 tugas2_2 tugas2_3_array tugas2_3_linked_list

all: $(TARGETS)

tugas2_1: tugas2_1.c
	$(CC) $(CFLAGS) -o $(ELF_DIR)tugas2_1 tugas2_1.c

tugas2_2: tugas2_2.c
	$(CC) $(CFLAGS) -o $(ELF_DIR)tugas2_2 tugas2_2.c

tugas2_3_array: tugas2_3_array.c
	$(CC) $(CFLAGS) -o $(ELF_DIR)tugas2_3_array tugas2_3_array.c

tugas2_3_linked_list: tugas2_3_linked_list.c
	$(CC) $(CFLAGS) -o $(ELF_DIR)tugas2_3_linked_list tugas2_3_linked_list.c

